# Generated by Django 6.0.3 on 2026-03-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_alter_usuario_email_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoservico',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento_servicos', to='barber.agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamentoservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento_servicos', to='barber.servico'),
        ),
        migrations.AlterField(
            model_name='disponibilidadefuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='barber.funcionario'),
        ),
    ]
